package com.petstore.entities;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Entity class for tag.
 * <p>
 * User: Ionut Barau (ionutbarau)
 * Project: petstore
 * Date: 21/04/2017.
 * Time: 16:27
 */
@Entity
public class Tag implements Serializable {

    /**
     * The serialVersionUID.
     */
    private static final long serialVersionUID = 8940226792088529946L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id")
    /** The tag id. */
    private Integer id;

    @Column(name = "name")
    /** The tag name. */
    private String name;

    /**
     * Default no-arg constructor.
     */
    public Tag() {
    }

    /**
     * Public constructor with all the fields as arguments.
     *
     * @param id
     * @param name
     */
    public Tag(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    //Generated by Intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Tag tag = (Tag) o;

        if (id != null ? !id.equals(tag.id) : tag.id != null) return false;
        return name != null ? name.equals(tag.name) : tag.name == null;

    }

    //Generated by Intellij
    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }

    //Generated by Intellij
    @Override
    public String toString() {
        return "Tag{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
